### ISSUE TITLE
SpamReport script has issues with removing messages from IMAP

### ISSUE THREAD

**Issue by alexkiro** [SpamExperts/SpamReporter#1]
When using the SpamRepoter script, and deleting messages they often re-populate after some time. 

This seems to be due to the script only marking them as removed and not actually removing them from the IMAP server. So if they login with a 2nd device to their own IMAP account the spam is re-populated on all devices.

**Comment by SageBrushes** [comment]
I experience this as well! I'll select a message as spam with a script but it will still show up on my iPhone!
