### ISSUE TITLE
CodecSmoke.3 Adware in install file?

### ISSUE THREAD

**Issue by alphi21** [SpamExperts/SpamReporter#4]
SpamReporterV4.0.dmg

### Steps to replicate

1. download SpamReporterV4.0.dmg from http://download.seinternal.com/mua/SpamReporterV4.0.dmg
2. double click to open SpamReporterV4.0.dmg

<img width="937" alt="spamreporter_osx_and_new" src="https://cloud.githubusercontent.com/assets/28729930/26103986/4d1099fc-3a7f-11e7-9a09-7d10132bba9a.png">

The contents of the dmg are shown briefly, before the window is closed automatically by Bitdefender Antivirus for Mac, presumably because  the following Adware was detected ...
_Gen:Variant.Adware.MAC.OSX.CodecSmoke.3 deleted
 
/Volumes/SpamReporter OSX/SpamReporter OSX.app/Contents/MacOS/Installer_
<img width="1037" alt="history_and_new_and_knowledgebase___mail_app_report_spam_tool_-_apple_osx" src="https://cloud.githubusercontent.com/assets/28729930/26104006/5e9b9a50-3a7f-11e7-983a-d2581fdd6dc7.png">

Is Bitdefender misreporting here, or is there adware here?

**Comment by alexkiro** [comment]
> Is Bitdefender misreporting here, or is there adware here?

There is no adware in the SpamReporter script. This seems like a False Positive from your Antivirus.
